version: "3"

services:
  redis:
    image: redis:5.0
    ports:
      - 6379:6379

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./infra/mysql/init/:/docker-entrypoint-initdb.d
      - ./infra/mysql/init/my.cnf:/etc/mysql/my.cnf
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  back:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8083:8083"
    volumes:
      - ./:/app/
    env_file:
      - .env
    depends_on:
      - redis
      - mysql

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - 3000:8080
    environment:
      SWAGGER_JSON: /api/api-document.yaml
    volumes:
      - ./docs/api-document.yaml:/api/api-document.yaml:ro

volumes:
  db-data:
    driver: local